knp_snappy:
  pdf:
    enabled: true
    binary: '"C:/Program Files/wkhtmltox-0.12.6-1.mxe-cross-win64/wkhtmltox/bin/wkhtmltopdf.exe"'
    options:
      enable-local-file-access: true
      encoding: "utf-8"
      margin-top: 10
      margin-bottom: 10
  image:
    enabled: true
    binary: '"C:/Program Files/wkhtmltox-0.12.6-1.mxe-cross-win64/wkhtmltox/bin/wkhtmltoimage.exe"'
    options: []
