parameters:
  image_directory: "%kernel.project_dir%/public/img"

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Security\authhandle:
    tags:
      - {
          name: kernel.event_listener,
          event: lexik_jwt_authentication.on_authentication_success,
          method: __invoke,
        }

  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"
