parameters:
  image_directory: "%kernel.project_dir%/public/img"
  uploads_directory: "%kernel.project_dir%/public/uploads"
  google_client_id: "%env(GOOGLE_CLIENT_ID)%"
  azure_api_endpoint: "https://models.inference.ai.azure.com/chat/completions"
  azure_api_token: "%env(AZURE_API_TOKEN)%"
  hcaptcha_site_key: "%env(HCAPTCHA_SITE_KEY)%"
  hcaptcha_secret: "%env(HCAPTCHA_SECRET)%"

services:
  # Default service configuration
  _defaults:
    autowire: true
    autoconfigure: true

  # Auto-register services from src/, excluding certain paths
  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"

  # Specific service definitions
  App\Service\MailService: ~

  App\Services\GoogleAuthenticator:
    arguments:
      $clientRegistry: "@knpu.oauth2.registry"
      $entityManager: "@doctrine.orm.entity_manager"
      $router: "@router"
      $jwtManager: "@lexik_jwt_authentication.jwt_manager"
    tags:
      - { name: "monolog.logger" }

  Symfony\Contracts\HttpClient\HttpClientInterface: "@http_client"

  App\Service\GeminiService:
    arguments:
      $pdfGenerator: "@knp_snappy.pdf"

  App\Service\PdfGeneratorService:
    arguments:
      $pdf: "@knp_snappy.pdf"

  App\EventSubscriber\EntretienHistorySubscriber:
    tags:
      - { name: "doctrine.event_subscriber" }

  App\Service\CvAnalyzerService:
    arguments:
      $apiEndpoint: "%azure_api_endpoint%"
      $apiToken: "%azure_api_token%"

  App\Controller\LoginController:
    arguments:
      $hcaptchaSiteKey: "%hcaptcha_site_key%"

  App\Service\HCaptchaService:
    arguments:
      $hcaptchaSecret: "%hcaptcha_secret%"
